### ISSUE TITLE
Use only real part of transfer function

### ISSUE THREAD

**Issue by mpross** [mpross/Single-Station-Seismology#4]

**Comment by mpross** [comment]
Real part allows us to toss out of phase component and thus drop out the horizontal coupling.

**Comment by raresionut1** [comment]
In order to extract the real part of the tf(transfer function) you must find the Fourier form of your tf.

In order to do that, you need to use "syms" (symbolic math), which is part of the Symbolic Math Toolbox.

**Comment by mpross** [comment]
Ended up not using the transfer function in the analysis
